workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    panora-open-api-swagger:
        inputs:
            - location: https://raw.githubusercontent.com/panoratech/Panora/main/packages/api/swagger/swagger-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/panora/panora/panora-open-api-swagger
targets:
    my-first-target:
        target: typescript
        source: panora-open-api-swagger
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/panora/panora/code-samples-typescript-my-first-target
